export const userSagaActions = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  CHECK_USER: 'CHECK_USER',
  SIGN_OUT: 'USER_SIGN_OUT',
  SIGN_UP: 'USER_SIGN_UP',
};
